name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies for Cloud Functions
        run: |
          cd functions
          npm ci

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: health-tracker-4075c
          channelId: live

      - name: Set Claude API Key in Firebase Config
        run: |
          npm install -g firebase-tools
          firebase functions:config:set claude.api_key="${{ secrets.CLAUDE_API_KEY }}" --token "${{ secrets.FIREBASE_TOKEN }}" --project health-tracker-4075c || echo "Config already set"

      - name: Deploy Cloud Functions
        run: |
          firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}" --project health-tracker-4075c
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
