name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies for Cloud Functions
        run: |
          cd functions
          npm ci

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: health-tracker-4075c
          channelId: live

      - name: Authenticate with Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-service-account.json

      - name: Set Claude API Key in Firebase Config
        run: |
          npm install -g firebase-tools
          firebase functions:config:set claude.api_key="${{ secrets.CLAUDE_API_KEY }}" --project health-tracker-4075c || echo "Config already set"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-service-account.json

      - name: Deploy Cloud Functions
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json
          npm install -g firebase-tools
          firebase deploy --only functions --project health-tracker-4075c --force
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
